# Generated by Django 3.2.4 on 2021-06-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('mot_de_passe', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('enonce', models.TextField(max_length=10000000)),
                ('name', models.CharField(max_length=50)),
                ('auteur', models.CharField(default='admin', max_length=20)),
                ('date', models.DateTimeField()),
                ('dure', models.DateTimeField()),
                ('niveau', models.CharField(choices=[('facile', 'facile'), ('normal', 'normal'), ('difficile', 'difficile')], max_length=20)),
                ('input', models.FloatField()),
                ('output', models.FloatField()),
            ],
        ),
    ]
